import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-center text-3xl">Hello Sentry</h1>

        <button
          type="button"
          onClick={() => {
            throw new Error('Sentry Frontend Error')
          }}
        >
          Throw error
        </button>

        <h2>環境変数漏れてないかチェック</h2>
        <p>SENTRY_DSN: {process.env.SENTRY_DSN}</p>
        <p>NEXT_PUBLIC_SENTRY_DSN: {process.env.NEXT_PUBLIC_SENTRY_DSN}</p>
        <p>{JSON.stringify(process.env)}</p>
      </main>
    </>
  )
}
